### ISSUE TITLE
Please add course titles to each tute tile or a key (ie this colour = this course)

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#144]
Thanks for putting this together

Label: Feature request

_Originally submitted by anonymous via the Microsoft Form_

**Comment by CraftyDH** [comment]
Do you think this is referring to our bug of the course titles not showing up, or a feature request for a legend?

**Comment by pl4nty** [comment]
@CraftyDH yeah I think so, I'll try and contact this user
