### ISSUE TITLE
Missing tutorials for POLS2119

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#148]
pretty much all the tutorials are missing for POLS2119, Tuesday 15:30-16:30, Wednesday 9-10, 10-11, 14-15, 17-18, Thursday 9-10, 10-11, 11-12, 14-15 and Friday 11-12 

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by CraftyDH** [comment]
Fixed the course code as an amend was posted on #149

**Comment by CraftyDH** [comment]
These events have been in the timetable data for a while now, therefor this must be some kind of client side issue. Possibly related to a service worker bug?

**Comment by pl4nty** [comment]
@CraftyDH iirc the serviceworker doesn't cache JSON. Haven't checked, but I suspect these tutorials start in Week 2 and the user didn't know to click next. Has happened a few times - not sure how to address, maybe an FAQ/guide?

**Comment by pl4nty** [comment]
Serviceworker has been removed, I think we can say this is fixed
