### ISSUE TITLE
Courses with multiple groups of events to choose from (eg a tute and a lab) only store one choice in the link and export

### ISSUE THREAD

**Issue by OliverBalfour** [anucssa/anutimetable#151]
Reported by rxw on Discord

Examples:
* COMP3620
* PHYS1101

If you pick a lab and a tute only the most recently picked choice saves to the querystring and exported ICS files/calendars

This requires a fix on the front-end and the GetICS function. We can just use a comma separated list in the query string, that's backwards compatible if anyone's stuck using an old version due to service worker shenanigans with the latest GetICS API.

**Comment by OliverBalfour** [comment]
I'll take a look at this on Saturday or Sunday if nobody jumps in before me

**Comment by OliverBalfour** [comment]
We've decided to use the query string format `?PHYS1101=PracA_2,WorA_1`, ie just having a comma separated list of selected events. This is backwards compatible (so calendars linked to GetICS don't regress) and human readable

**Comment by pl4nty** [comment]
GetICS is already compatible with the format `?PHYS1101=PracA2,WorA1`, would much prefer to stick with it as changes would break backwards compatibility. Looks like just the frontend behaviour needs fixing
