### ISSUE TITLE
Selecting hidden days doesn't work on Safari (IOS)

### ISSUE THREAD

**Issue by CraftyDH** [anucssa/anutimetable#153]
It comes up with a selection tool where you can select excluded days. However, it doesn't save / action anything.

**Comment by pl4nty** [comment]
I silently patched this in the responsive branch soz, onMouseDown didn't work on mobile

**Comment by CraftyDH** [comment]
Just checked on the responsive PR, still doesn't work at least on my phone.

**Comment by pl4nty** [comment]
Fixed on Android in #127, @CraftyDH any chance you can test on iOS?

**Comment by CraftyDH** [comment]
Can confirm that the bug is fixed on IOS in #127!
