### ISSUE TITLE
COMP1100 lab time

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#154]
COMP1100 has lab time, but on the timetable, I cannot find the lab time of COMP1100

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by CraftyDH** [comment]
I think this is another issue of people not realising that some tuts start in week 2.

**Comment by pl4nty** [comment]
@CraftyDH apparently Ranald is doing week 1 tutes, but timetabling haven't updated yet. I don't really want to get involved in unofficial data sources.
