### ISSUE TITLE
GEND1001 Class Times Update

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#164]
Hi there, 
i hope you are staying safe! I've just tried to build my timetable with the unofficial builder and I've noticed that the updated times for GEND1001 haven't been uploaded, they changed the times sometime this week so completely different times :(, if you lovely peeps could update this it would be greatly appreciated! the times are as on the official anu timetable!
thank you :)

Label: GEND1001 classes not updated

_Originally submitted by anonymous via the Microsoft Form_

**Comment by CraftyDH** [comment]
Will be fixed by #166
