### ISSUE TITLE
Too zoomed in

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#180]
The items and blocks are too big. I have to scroll down to look at the schedule for the whole day. Its really inconvenient to looking at the weeks schedule as a whole as I have to scroll down. Please make it so that all items in the week can fit on screen at the same time. Thank you :)  

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by CraftyDH** [comment]
Will be fixed by #127.

**Comment by CraftyDH** [comment]
Fixed by #127
