### ISSUE TITLE
The timeline is wrong

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#185]
Its not that the times of the classes themselves are up to date, its that the whole thing reads and hour and a half behind the actual time. So its 10:15 when I'm writing this, on the time table its says its 8:45.

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by CraftyDH** [comment]
The user has possibly selected a Timezone an hour and a half behind canberra.

**Comment by pl4nty** [comment]
Agreed, not sure if we can improve the UX here
