### ISSUE TITLE
Semester 2 courses to be included in unofficial timetable

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#188]
Label: Feature request

_Originally submitted by anonymous via the Microsoft Form_

**Comment by CraftyDH** [comment]
AFAIK some courses are when you select S2. However ANU hasn't published the times for most classes yet.

**Comment by pl4nty** [comment]
Should we add a warning banner or something? Maybe worth asking timetabling if they plan to update the old official timetable

**Comment by pl4nty** [comment]
Fixed in 3470ee7c7b6dce45032f57309cbcfa7a49493880
