### ISSUE TITLE
Missing lecture for Course MATH6405

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#189]
This is being written to inform you about a minor error regarding the MATH6405 course.
There is a lecture every Wednesday between 3:00 to 4:00 for the MATH6405 course that has yet to be added to the Calender. 
Kindly make this necessary addendum as soon as possible. Thank you in advance.

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by CraftyDH** [comment]
Closing as this should be reflected in the offical data source soon.
