### ISSUE TITLE
Buttons/text sometimes truncated

### ISSUE THREAD

**Issue by angussidney** [anucssa/anutimetable#30]
(I'm sure you're probably aware of this, and I know that you're no longer actively working on this, but it could be a lower-dpi screen issue that you haven't noticed on your screen, so I thought I'd report it anyway)

If the text/buttons are too big to fit within a timetable entry (because the class is short or the location description is long), the choose buttons are sometimes truncated and unclickable:

![image](https://user-images.githubusercontent.com/4848802/148372348-dfa1f1a0-436d-4648-a1b9-ee4f8882c06c.png)

The existing timetable works around this by expanding the size of the cells:

![image](https://user-images.githubusercontent.com/4848802/148372741-7b1ba02a-3d5b-4b13-a905-cb14585e56c9.png)

An alternate workaround could possibly be to collapse the text to 2 lines, and provide an 'info' button that can expand the full timetable entry.

**Comment by pl4nty** [comment]
Thanks for raising this, and I appreciate the detailed screenshots 👍 
I removed the buttons entirely in #31, in favour of "tap to choose" behaviour. Not sure if it's particularly good UX though (especially without a tooltip/explanation somewhere), what do you think? It also doesn't support delete-by-click, but that would be an easy fix for single-instance events like lectures.

**Comment by pl4nty** [comment]
And text truncation remains a problem:

![image](https://user-images.githubusercontent.com/21111317/148683746-4b88e5f6-1e88-4159-b30e-b74c9022d289.png)
