### ISSUE TITLE
Approval workflow for CI on PRs from forks

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#34]
Currently PRs from forks run in the fork context (pull_request) and don't have access to deploy creds, so fail. Seems like a regression related to pull_request_target, but we need a secure workflow to approve CI for a build and avoid credential theft risks (contributors to approve?).

**Comment by OliverBalfour** [comment]
I have direct push access to this repo (made a branch on my old fork for the license by mistake) so this is a slightly lower priority

**Comment by pl4nty** [comment]
We should also avoid creating a staging environment if changes have only been made to /scraper
