### ISSUE TITLE
Display current timezone and option to use Canberra time 

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#37]
Next to header?

**Comment by angussidney** [comment]
Can we potentially add a 'Switch to Canberra time' button? My browser's privacy settings makes the timetable think I'm in the UTC timezone. (would also be useful for international students planning their timetable before they arrive in Australia).

**Comment by pl4nty** [comment]
Good idea. We could do a full timezone selection dropdown, but that might clutter the UI (and users may not realise the timetable has autodetection).

Can just do a conditional subheading (tz != cbr) - "Displaying times in [timezone]. To view in Canberra time, click here". Should flag in storage, but localStorage wouldn't be reversible without a UI element. So maybe sessionStorage? Adds a click for privacy browsers in every session, but persists across reloads/restores at least.

**Comment by OliverBalfour** [comment]
Added a dropdown in #48. Useful if you are overseas and want to switch between viewing in local and Canberra time
