### ISSUE TITLE
Add academic week next to the dates of the week (enhancement)

### ISSUE THREAD

**Issue by harry-hart** [anucssa/anutimetable#47]
As title, just display the week number with the dates for ease of use. Excited to watch the project grow!

**Comment by pl4nty** [comment]
Just to clarify, is this adding the week number to the title in the Week view? ie new title would be Jan 10 – 14 (Week 2), 2022
It's already visible in the top-left corner, but I'm happy to make it more prominent.

![image](https://user-images.githubusercontent.com/21111317/149270087-bdbb2720-6b4f-48a7-ac8a-7ed7de0a1010.png)

Setting `views.timeGridDay.titleFormat.week` might work, but I think I remember an upstream bug that prevented using week with other [format options](https://fullcalendar.io/docs/titleFormat).

**Comment by harry-hart** [comment]
Oh, my bad I did miss that! Happy how it is.

**Comment by OliverBalfour** [comment]
Fixed in #48
