### ISSUE TITLE
ICS export includes all lab times

### ISSUE THREAD

**Issue by OliverBalfour** [anucssa/anutimetable#51]
To reproduce:
* Visit https://timetable.cssa.club/?y=2022&s=S1&MATH2320=WorA2&COMP2300=ComA7&COMP4670=ComA4
* Export > any option

All of the lab times show up in your calendar, not just the selected ones

**Comment by pl4nty** [comment]
RCA to regression from dropping the leading 0 in client-side occurrences, should be an easy fix
