### ISSUE TITLE
Choose button cut off when the window is too short

### ISSUE THREAD

**Issue by OliverBalfour** [anucssa/anutimetable#64]
Looks like our calendar library tries to intelligently change its height and fails. Should stay a static height imo, that's why the scrollbar is there

**Comment by pl4nty** [comment]
Was just mentioned in ANU Students, we'll probably have to prioritise this

**Comment by pl4nty** [comment]
Maybe an [Overlay Trigger](https://react-bootstrap-v4.netlify.app/components/overlays/#overlay-trigger) nesting the button?

**Comment by OliverBalfour** [comment]
> Maybe an [Overlay Trigger](https://react-bootstrap-v4.netlify.app/components/overlays/#overlay-trigger) nesting the button?

I'm not sure I understand, could you elaborate?

**Comment by pl4nty** [comment]
was just a thought, in hindsight it might not be possible. was thinking if we could detect truncated events, and render an overlay on hover containing the truncated details

**Comment by pl4nty** [comment]
@OliverBalfour happy to close this as fixed, pending further feedback?

**Comment by OliverBalfour** [comment]
Yep sounds good
