### ISSUE TITLE
Selecting top item in course dropdown opens timezone selector instead

### ISSUE THREAD

**Issue by angussidney** [anucssa/anutimetable#76]
See ~~jif~~ gif:
![timetable select](https://user-images.githubusercontent.com/4848802/149645896-83d358d6-74be-4795-a98e-35536522923d.gif)

**Comment by pl4nty** [comment]
Can you share the browser you're using? In my local Edge and Firefox, the dropdown detects mouseover and responds with a pointer mouse and gray highlight as below. This doesn't seem to be happening in your gif and might be related,

![image](https://user-images.githubusercontent.com/21111317/149646084-c4028989-7139-4f02-b6d5-a401706a8d00.png)

**Comment by angussidney** [comment]
Currently using Firefox 95.0.1 on PopOS 18.04. I've just checked, the hover effect works on all but the first item. Seems to be working fine in chromium - I might try disabling extensions and updating my browser and see if I still have issues.

**Comment by OliverBalfour** [comment]
I've got FF 95.0.2 and Chrome 95 on Manjaro Linux and both work. Strange.

**Comment by angussidney** [comment]
Okay, I've narrowed down the issue. This only occurs if no timezone is selected. When I select a timezone, it works fine. 

Note that when no timezone is selected, the placeholder text is simply 'Select...' (as you can see in the GIF), which is why I created #80, and hence how I have discovered this problem. (cc @OliverBalfour because you mentioned that you couldn't see the effect of my PR - that's probably why)

**Comment by pl4nty** [comment]
apologies for the accidental link, if it closes this issue I'll reopen it

**Comment by pl4nty** [comment]
@angussidney the user's local timezone is selected by default, since we need it to render events. so we can't actually have a placeholder unfortunately. maybe a [Tooltip](https://react-bootstrap.github.io/components/overlays/#tooltips) could work?

**Comment by angussidney** [comment]
Hmmm.... that's really weird - because the timezone wasn't selected by default for me. If we can fix the timezone selection bug, then a placeholder is totally unnecessary.

**Comment by pl4nty** [comment]
oh! good to know, it wasn't tested on firefox, hence #81. I'll get on that now

**Comment by pl4nty** [comment]
@angussidney any chance you can run the following in your browser's JS console?
```js
Intl.DateTimeFormat().resolvedOptions().timeZone
```
I haven't been able to replicate and MDN has it supported since v53, so maybe it's blocked by a privacy setting?

**Comment by angussidney** [comment]
![image](https://user-images.githubusercontent.com/4848802/149647540-1a673153-47d2-45d9-bae5-010c5a329552.png)
 Probably a privacy setting. Maybe we should fallback to canberra time if the timezone fails?

**Comment by pl4nty** [comment]
Turns out the timezone dropdown uses "Etc/GMT" for UTC, so we should probably just respect the browser's timezone. The dropdown persists so users can always override anyway. Added to the fixes in #81.
