### ISSUE TITLE
Course colours can contrast poorly

### ISSUE THREAD

**Issue by pl4nty** [anucssa/anutimetable#77]
Not sure on a cause, but there are some pretty awful combos eg https://timetable.cssa.club/?y=2022&s=S1&BIOL1003=&SCOM1001=&CHEM1101=

**Comment by OliverBalfour** [comment]
I changed the colour selection to be HSL with only the hue varying to avoid light yellows with white text, and I guess that vastly increases the likelihood of clashing colours

Idea 1: What we could do is not associate a colour to each course, but have a fixed list of colours with different hues that we pick from (but then of course adding/removing courses may make them change colours...)

Idea 2: Fixed list of colours, cache the colours to localStorage and never reallocate colours to a different course. That's the least likely to mess anything up I guess. You'll get different colours on different browsers but that's the best we can do unless we let users customise the colour

**Comment by OliverBalfour** [comment]
Fixed in #83
